version: "3.9"

services:

  rollout:
    build:
      context: ./
      dockerfile: Dockerfile.debug
    volumes:
      - ./app:/opt/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET=${SECRET:?Please provide the webhook token!}
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
