name: PUBLISH

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        id: build
        env:
          GITHUB_TOKEN: ${{ matrix.platform.app }}
        run: |
          export VERSION=$(echo ${{ github.ref }} | cut -d / -f 3)

          export IMAGE=ghcr.io/${{ github.repository }}:$VERSION
          export PLATFORMS=linux/amd64,linux/arm64

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

          docker buildx create --name local-build
          docker buildx use local-build

          docker buildx b --platform $PLATFORMS --build-arg APP_VERSION=$APP_VERSION -t $IMAGE --push .
